jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      ...
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/term-suggestion/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4